version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user_name
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: my_authentication
    ports:
     - "5432:5432"
     
    volumes:
     - postgres_data:/var/lib/postgresql/postgres_data
    
volumes:
  postgres_data: